 
export const ROLES = {
  ADMIN: 'admin',
  REGULAR: 'regular'
};

export const TASK_STATUS = {
  SET_TASKS: 'SET_TASKS',
  ADD_TASK: 'ADD_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_SAVING: 'SET_SAVING',
  SET_DELETING: 'SET_DELETING',
  SET_UPDATING: 'SET_UPDATING',
};
